[package]
name = "qscv-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
thiserror = "2.0.12"
tokio = { version = "1.44.1", optional = true, features = ["io-util","net","sync","time","rt"] }

[features]
migration = []
tokio = ["dep:tokio"]
