[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
qs = { version = "0.1.0", path = "../qs", features = ["tokio"] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
