[package]
name = "qscv"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = "0.11.3"

[workspace]
members = [ "codegen","postgres-protocol", "postgres-types"]
default-members = [ ".","postgres-protocol", "postgres-types"]
