[package]
name = "postgres-types"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
fallible-iterator = "0.3.0"
postgres-protocol = { version = "0.1.0", path = "../postgres-protocol" }
