[package]
name = "postgres-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
byteorder = "1.5.0"
bytes = "1.10.1"
fallible-iterator = "0.3.0"
hmac = "0.12.1"
md-5 = "0.10.6"
memchr = "2.7.4"
rand = "0.9.0"
sha2 = "0.10.8"
stringprep = "0.1.5"
